### ISSUE TITLE
LDK 0.1.9 Roadmap

### ISSUE THREAD

**Issue by lgou2w** [lgou2w/ldk#88]
## 0.1.8 Stable Version
- [x] Kotlin 1.3.40
- [x] Kotlin Coroutines 1.3.0
- [x] Final optimization

### Enhancement

- [x] Add `ldk-plugin` module.
- [x] Add `ldk-eventbus` module.
- [x] Add `ldk-eventbus-common` module.
- [x] Add `ldk-eventbus-asm` module.

### Module change

- [x] Remove `ldk-fx` all modules.
- [x] Remove `ldk-rx` and `ldk-bukkit-rx` modules.
- [x] Rename `ldk-rsa` to `ldk-security` module. And the package moved to `com.lgou2w.ldk.security`.

**Comment by lgou2w** [comment]
0.1.9 Released !
